"""Initial schema

Revision ID: 0fc409310dd0
Revises: 
Create Date: 2026-02-21 18:50:41.436082

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '0fc409310dd0'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gen_instant',
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gen_instant_id'), 'gen_instant', ['id'], unique=False)
    op.create_index(op.f('ix_gen_instant_timestamp'), 'gen_instant', ['timestamp'], unique=True)
    op.create_table('source',
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('renewable', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_source_id'), 'source', ['id'], unique=False)
    op.create_table('gen_source',
    sa.Column('gen', sa.Float(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('gen_instant_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['gen_instant_id'], ['gen_instant.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gen_source_id'), 'gen_source', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gen_source_id'), table_name='gen_source')
    op.drop_table('gen_source')
    op.drop_index(op.f('ix_source_id'), table_name='source')
    op.drop_table('source')
    op.drop_index(op.f('ix_gen_instant_timestamp'), table_name='gen_instant')
    op.drop_index(op.f('ix_gen_instant_id'), table_name='gen_instant')
    op.drop_table('gen_instant')
    # ### end Alembic commands ###
